CREATE TABLE IF NOT EXISTS cities (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    country VARCHAR(80) NOT NULL DEFAULT 'Pakistan',
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_cities_name_country (name, country),
    INDEX idx_cities_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT IGNORE INTO cities (name, country, is_active) VALUES
('Islamabad', 'Pakistan', 1),
('Karachi', 'Pakistan', 1),
('Lahore', 'Pakistan', 1),
('Rawalpindi', 'Pakistan', 1),
('Faisalabad', 'Pakistan', 1),
('Multan', 'Pakistan', 1),
('Peshawar', 'Pakistan', 1),
('Quetta', 'Pakistan', 1),
('Hyderabad', 'Pakistan', 1),
('Gujranwala', 'Pakistan', 1),
('Sialkot', 'Pakistan', 1),
('Sukkur', 'Pakistan', 1),
('Larkana', 'Pakistan', 1),
('Bahawalpur', 'Pakistan', 1),
('Bahawalnagar', 'Pakistan', 1),
('Rahim Yar Khan', 'Pakistan', 1),
('Dera Ghazi Khan', 'Pakistan', 1),
('Muzaffargarh', 'Pakistan', 1),
('Layyah', 'Pakistan', 1),
('Rajanpur', 'Pakistan', 1),
('Khanewal', 'Pakistan', 1),
('Vehari', 'Pakistan', 1),
('Lodhran', 'Pakistan', 1),
('Okara', 'Pakistan', 1),
('Sahiwal', 'Pakistan', 1),
('Pakpattan', 'Pakistan', 1),
('Kasur', 'Pakistan', 1),
('Sheikhupura', 'Pakistan', 1),
('Nankana Sahib', 'Pakistan', 1),
('Gujrat', 'Pakistan', 1),
('Jhelum', 'Pakistan', 1),
('Chakwal', 'Pakistan', 1),
('Attock', 'Pakistan', 1),
('Wah Cantt', 'Pakistan', 1),
('Mandi Bahauddin', 'Pakistan', 1),
('Hafizabad', 'Pakistan', 1),
('Narowal', 'Pakistan', 1),
('Sargodha', 'Pakistan', 1),
('Khushab', 'Pakistan', 1),
('Mianwali', 'Pakistan', 1),
('Bhakkar', 'Pakistan', 1),
('Jhang', 'Pakistan', 1),
('Chiniot', 'Pakistan', 1),
('Toba Tek Singh', 'Pakistan', 1),
('Peshawar', 'Pakistan', 1),
('Charsadda', 'Pakistan', 1),
('Nowshera', 'Pakistan', 1),
('Mardan', 'Pakistan', 1),
('Swabi', 'Pakistan', 1),
('Kohat', 'Pakistan', 1),
('Karak', 'Pakistan', 1),
('Hangu', 'Pakistan', 1),
('Bannu', 'Pakistan', 1),
('Lakki Marwat', 'Pakistan', 1),
('Dera Ismail Khan', 'Pakistan', 1),
('Tank', 'Pakistan', 1),
('Abbottabad', 'Pakistan', 1),
('Haripur', 'Pakistan', 1),
('Mansehra', 'Pakistan', 1),
('Battagram', 'Pakistan', 1),
('Alpuri', 'Pakistan', 1),
('Mingora', 'Pakistan', 1),
('Daggar', 'Pakistan', 1),
('Batkhela', 'Pakistan', 1),
('Timergara', 'Pakistan', 1),
('Dir', 'Pakistan', 1),
('Chitral', 'Pakistan', 1),
('Parachinar', 'Pakistan', 1),
('Miranshah', 'Pakistan', 1),
('Wana', 'Pakistan', 1),
('Karachi', 'Pakistan', 1),
('Thatta', 'Pakistan', 1),
('Sujawal', 'Pakistan', 1),
('Badin', 'Pakistan', 1),
('Jamshoro', 'Pakistan', 1),
('Matiari', 'Pakistan', 1),
('Tando Allahyar', 'Pakistan', 1),
('Tando Muhammad Khan', 'Pakistan', 1),
('Dadu', 'Pakistan', 1),
('Qambar', 'Pakistan', 1),
('Shikarpur', 'Pakistan', 1),
('Jacobabad', 'Pakistan', 1),
('Kashmore', 'Pakistan', 1),
('Ghotki', 'Pakistan', 1),
('Khairpur', 'Pakistan', 1),
('Naushahro Feroze', 'Pakistan', 1),
('Shaheed Benazirabad', 'Pakistan', 1),
('Sanghar', 'Pakistan', 1),
('Mirpur Khas', 'Pakistan', 1),
('Umerkot', 'Pakistan', 1),
('Mithi', 'Pakistan', 1),
('Quetta', 'Pakistan', 1),
('Pishin', 'Pakistan', 1),
('Ziarat', 'Pakistan', 1),
('Mastung', 'Pakistan', 1),
('Kalat', 'Pakistan', 1),
('Khuzdar', 'Pakistan', 1),
('Uthal', 'Pakistan', 1),
('Hub', 'Pakistan', 1),
('Awaran', 'Pakistan', 1),
('Turbat', 'Pakistan', 1),
('Panjgur', 'Pakistan', 1),
('Gwadar', 'Pakistan', 1),
('Dalbandin', 'Pakistan', 1),
('Nushki', 'Pakistan', 1),
('Kharan', 'Pakistan', 1),
('Sibi', 'Pakistan', 1),
('Harnai', 'Pakistan', 1),
('Kohlu', 'Pakistan', 1),
('Dera Bugti', 'Pakistan', 1),
('Loralai', 'Pakistan', 1),
('Barkhan', 'Pakistan', 1),
('Gilgit', 'Pakistan', 1),
('Skardu', 'Pakistan', 1),
('Astore', 'Pakistan', 1),
('Chilas', 'Pakistan', 1),
('Gahkuch', 'Pakistan', 1),
('Khaplu', 'Pakistan', 1),
('Shigar', 'Pakistan', 1),
('Muzaffarabad', 'Pakistan', 1),
('Mirpur', 'Pakistan', 1),
('Kotli', 'Pakistan', 1),
('Bhimber', 'Pakistan', 1),
('Rawalakot', 'Pakistan', 1),
('Bagh', 'Pakistan', 1),
('Pallandri', 'Pakistan', 1),
('Athmuqam', 'Pakistan', 1),
('Hattian Bala', 'Pakistan', 1);
